# Workflow configuration for deploying a Dockerized app to Heroku
name: Deploy to Heroku

# Run workflow on every push to the main branch
on:
  push:
    branches:
      - main

# Define the workflow jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build, Push, and Release the Docker container to Heroku
      - name: Build, Push, and Release to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # Email associated with your Heroku account
          email: ${{ secrets.HEROKU_EMAIL }}

          # Heroku API Key
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Heroku App Name
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}

          # Dockerfile directory (default: "./")
          dockerfile_directory: ./

          # Dockerfile name (default: "Dockerfile")
          dockerfile_name: Dockerfile

          # Additional Docker build options (optional)
          docker_options: "--no-cache"

          # Process type (default: "web")
          process_type: web
